FROM alpine:3.6

# Install mongodb 3.4.4
RUN apk --update add mongodb mongodb-tools
RUN mkdir -p /data/db /var/dump/db
COPY basic-dataset.zip .
RUN apk update && apk add  unzip && unzip basic-dataset.zip -d /var/dump/

EXPOSE 27017
CMD ["mongod"]